controller_manager:
  ros__parameters:
    update_rate: 1000 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    PD_control:
      type: rbt_pd_cnt/Rbt_PD_cnt
PD_control:
    ros__parameters:
      joint:
      - LF_HFE
      - LF_KFE
      - RF_HFE
      - RF_KFE
      - LH_HFE
      - LH_KFE
      - RH_HFE
      - RH_KFE
      K_d: 0.4
      K_p: 40.0
      # K_d: 0.6
      # K_p: 80.0
      # init_pos:
      #   - 0.0
      #   - 0.0
      #   - 0.0
      #   - 0.0
      #   - 0.0
      #   - 0.0
      #   - 0.0
      #   - 0.0
      #   - 0.0
      #   - 0.0
      #   - 0.0
      #   - 0.0

      init_pos:
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
      use_sim_time: True

joint_state_broadcaster:
  ros__parameters:
    joints:
    - LF_HFE
    - LF_KFE
    - RF_HFE
    - RF_KFE
    - LH_HFE
    - LH_KFE
    - RH_HFE
    - RH_KFE
    use_sim_time: True
    interfaces:
      - position
      - velocity 
      - effort