controller_manager:
  ros__parameters:
    update_rate: 1000 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    PD_control:
      type: rbt_pd_cnt/Rbt_PD_cnt
PD_control:
  ros__parameters:
    joint:
      - LF_HFE
      - LH_HFE
      - RF_HFE
      - RH_HFE
      - LF_KFE
      - LH_KFE
      - RF_KFE
      - RH_KFE

    K_d:
      - 0.4
      - 0.4
      - 0.4
      - 0.4
      - 0.4
      - 0.4
      - 0.4
      - 0.4
      
    K_p: 
      - 70.9
      - 70.9
      - 70.9
      - 70.9
      - 70.9
      - 70.9
      - 70.9
      - 70.9

    init_pos:
      - 2.0944
      - -2.0944
      - -2.0944
      - 2.0944
      - -1.0472
      - 1.0472
      - 1.0472
      - -1.0472
    use_sim_time: True

joint_state_broadcaster:
  ros__parameters:
    joints:
      - LF_HFE
      - LH_HFE
      - RF_HFE
      - RH_HFE
      - LF_KFE
      - LH_KFE
      - RF_KFE
      - RH_KFE
    use_sim_time: True
    # interfaces:
    #   - position
    #   - velocity
    #   - effort
