controller_manager:
  ros__parameters:
    update_rate: 1000 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    PD_control:
      type: rbt_pd_cnt/Rbt_PD_cnt
PD_control:
  ros__parameters:
    joint:
      - LF_HFE
      - LH_HFE
      - RF_HFE
      - RH_HFE
      - LF_KFE
      - LH_KFE
      - RF_KFE
      - RH_KFE
    # - LF_HFE
    # - LF_KFE
    # - RF_HFE
    # - RF_KFE
    # - LH_HFE
    # - LH_KFE
    # - RH_HFE
    # - RH_KFE
    K_d:
      - 2.0
      - 2.0
      - 2.0
      - 2.0
      - 0.025
      - 0.025
      - 0.025
      - 0.025
      
    K_p: 
      - 50.0
      - 50.0
      - 50.0
      - 50.0
      - 5.0 
      - 5.0
      - 5.0
      - 5.0
      # - 5.0
      # - 5.0
      # - 5.0 
      # - 5.0     


    # K_d: 0.6
    # K_p: 80.0
    # init_pos:
    #   - 0.0
    #   - 0.0
    #   - 0.0
    #   - 0.0
    #   - 0.0
    #   - 0.0
    #   - 0.0
    #   - 0.0
    #   - 0.0
    #   - 0.0
    #   - 0.0
    #   - 0.0
    init_pos:
      - 2.094
      - -2.094
      - -2.094
      - 2.094
      - -1.0471975511965976
      - 1.0471975511965976
      - 1.0471975511965976
      - -1.0471975511965976
      # - -0.7854
      # - 0.7854
      # - 0.7854
      # - -0.7854
    use_sim_time: True

joint_state_broadcaster:
  ros__parameters:
    joints:
      - LF_HFE
      - LH_HFE
      - RF_HFE
      - RH_HFE
      - LF_KFE
      - LH_KFE
      - RF_KFE
      - RH_KFE
    use_sim_time: True
    # interfaces:
    #   - position
    #   - velocity
    #   - effort
